### ISSUE TITLE
Actividad 10 corregida: Tengo dudas (ver descripción)

### ISSUE THREAD

**Issue by cborcar637** [Amaetor/Actividad-TIC#10]
La actividad no está mal, pero la forma de hacerlo es muy distinta a como hemos estudiado en clase, tengo mis dudas sobre si el código está hecho por ti, por otra persona o por una IA. Por ahora dejo la actividad sin calificar hasta saber qué ha pasado

**Comment by Amaetor** [comment]
Lo hice con w3school y el for lo hice con ia porque no sabia como hacer esa
actividad

**Comment by cborcar637** [comment]
De acuerdo, entonces está bien. No era necesario usar un bucle for, pero deja el código más limpio. Cierro la solicitud
